-- Admin-directed 5-question chat spine.
--
-- Replaces the single ai_predicted_next_question / per-snippet
-- follow_up_question pattern with an ORDERED ARRAY of up to 5
-- questions the admin uses to direct the coaching conversation
-- after onboarding. The AI prefills the 5; the admin edits any
-- subset before clicking Publish; the state-machine chat walks
-- the user through them in order.
--
-- Shape (both columns):
--   [
--     { "position": 1, "text": "...", "intent_tag": "ground-emotion" },
--     { "position": 2, "text": "...", "intent_tag": "test-application" },
--     ...
--   ]
-- intent_tag is a soft free string (no DB enum) so the model can
-- pick from any plausible vocabulary; we'll use it as a per-
-- position fine-tuning signal later.
--
-- DOES NOT drop existing ai_predicted_next_question / related
-- single-question fields — those keep working during the
-- transition. They become read-fallback only once the new admin
-- UI ships.
--
-- Run in Supabase SQL Editor. Idempotent.

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'v2_sessions'
      AND column_name = 'ai_predicted_next_questions'
  ) THEN
    ALTER TABLE v2_sessions
      ADD COLUMN ai_predicted_next_questions JSONB DEFAULT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'v2_sessions'
      AND column_name = 'final_human_next_questions'
  ) THEN
    ALTER TABLE v2_sessions
      ADD COLUMN final_human_next_questions JSONB DEFAULT NULL;
  END IF;
END $$;

COMMENT ON COLUMN v2_sessions.ai_predicted_next_questions IS
  'AI-prefilled ordered question script (up to 5). JSONB array of '
  '{position: 1..5, text: str, intent_tag?: str}. Generated by '
  'services.session_predictions during finalize. Replaces the '
  'single ai_predicted_next_question (which is kept read-only '
  'for back-compat with the old admin UI).';

COMMENT ON COLUMN v2_sessions.final_human_next_questions IS
  'Admin-edited or accepted version of the script, saved on '
  'POST /v2/admin/sessions/<id>/publish. State-machine chat '
  'prefers this over ai_predicted_next_questions when both '
  'exist. Per-position (predicted, final) pair becomes one row '
  'per question in admin_annotations_log for granular RLHF.';
