-- video_shown column is no longer used by the backend.
-- The waiting screen after lesson completion is handled by the /logged-out redirect (frontend).
-- This file is kept for reference only; do not run it.
--
-- To roll back if the column was already added:
--   ALTER TABLE v2_student_overrides DROP COLUMN IF EXISTS video_shown;
