-- Migration: coaching_sessions
--
-- One row per "click on a stress snippet" → micro-coaching loop. The loop
-- has two technical stages (awareness → trial) with a mini-reframe baked
-- into the awareness prompt:
--
--   awareness: bot serves the admin's comment + a one-shot reframe and
--              scenario setup. UI default = text input.
--   trial:     UI flips to record-only. The user re-performs the same
--              scenario with the new mindset; the audio runs through the
--              standard recording-1 analysis pipeline and produces a new
--              v2_session row whose snippets land back on /results.
--   complete:  trial recording bound, pipeline enqueued.
--
-- v1 is stress-only; the `intent` enum already accepts 'charisma' so the
-- charisma flow drops in next week with just new prompt strings.
--
-- Lifecycle: rows are append-only — we never UPDATE current_stage back
-- to a previous value, so the audit trail of how a user moved through
-- the loop is reconstructable from created_at / updated_at deltas.

CREATE TABLE IF NOT EXISTS coaching_sessions (
    id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    -- The snippet the user clicked from /results to start this loop.
    -- Carries the admin_comment that becomes the awareness "first bubble".
    source_snippet_id  UUID        NOT NULL REFERENCES charisma_snippets(id) ON DELETE CASCADE,

    intent             TEXT        NOT NULL
        CHECK (intent IN ('stress', 'charisma')),
    current_stage      TEXT        NOT NULL DEFAULT 'awareness'
        CHECK (current_stage IN ('awareness', 'trial', 'complete')),

    -- Bumped if the user re-runs the same loop on the same snippet.
    -- Currently always 1 in v1; reserved for the multi-loop iteration.
    loop_count         INT         NOT NULL DEFAULT 1,

    -- Bound when the user finishes the trial recording — its
    -- v2_sessions row is the parent of any new snippets the loop
    -- generates. NULL while the trial hasn't been recorded yet.
    trial_session_id   UUID        REFERENCES v2_sessions(id) ON DELETE SET NULL,

    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at       TIMESTAMPTZ
);

-- Owner lookups: "all coaching sessions for user X" + "the in-flight
-- coaching session for snippet Y" (a partial index since complete rows
-- don't need to be in this hot path).
CREATE INDEX IF NOT EXISTS idx_coaching_sessions_user_id
    ON coaching_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_coaching_sessions_source_snippet
    ON coaching_sessions(source_snippet_id);
CREATE INDEX IF NOT EXISTS idx_coaching_sessions_active
    ON coaching_sessions(user_id, current_stage)
    WHERE current_stage <> 'complete';

COMMENT ON TABLE coaching_sessions IS
    'Micro-coaching loop state. One row per stress/charisma snippet click. '
    'Stage transitions are forward-only (awareness → trial → complete).';

COMMENT ON COLUMN coaching_sessions.intent IS
    'Drives which set of stage prompts the LLM uses. v1 = stress only; '
    'charisma uses identical scaffolding with different prompts.';

COMMENT ON COLUMN coaching_sessions.trial_session_id IS
    'Bound after the trial recording is processed. The v2_sessions row '
    'whose snippets are the "evidence" generated by this loop.';
