"""Canonical contracts for coach-correctable LLM surfaces.

One surface owns one annotation-field set, one golden evaluation adapter, and
one runtime model slot.  Keeping this mapping in one place prevents a model
trained on one kind of correction from leaking into an unrelated generator.
"""
from __future__ import annotations

import contextvars
import re
import threading
import time
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Callable, Iterator, Optional

from services.mlc2_foundation import REJECTED_LEARNING_ALIASES


@dataclass(frozen=True)
class SurfaceContract:
    id: str
    annotation_fields: tuple[str, ...]
    runtime_aliases: tuple[str, ...]
    golden_eval_surface: str

    @property
    def runtime_config_key(self) -> str:
        return f"openai_surface_model_{self.id}"


SURFACES: dict[str, SurfaceContract] = {
    "say_it_stronger": SurfaceContract(
        id="say_it_stronger",
        annotation_fields=("say_it_stronger",),
        runtime_aliases=("say_it_stronger",),
        golden_eval_surface="say_it_stronger",
    ),
    # This is the contextual presentation-coach note, generated by
    # ``services.coach_comment_drafter`` and corrected in
    # ``coach_snippet_drafts.note``.  It is deliberately NOT the older
    # one-sentence ``admin_comment``/``snippet_drafts`` task: those prompts
    # and outputs have different semantics and must not share a corpus or a
    # promoted model merely because both happen to be called "comments".
    "coach_comment_draft": SurfaceContract(
        id="coach_comment_draft",
        annotation_fields=("coach_note",),
        runtime_aliases=("coach_comment_draft",),
        golden_eval_surface="coach_comment_draft",
    ),
    # ``best_presentation`` is the historical code/eval name.  The product
    # abstraction is Ideal Text, so both names resolve to one model slot.
    "ideal_text": SurfaceContract(
        id="ideal_text",
        annotation_fields=("ideal_text_sentence", "ideal_text_block"),
        runtime_aliases=("ideal_text", "best_presentation"),
        golden_eval_surface="best_presentation",
    ),
}

# E-6 (audit 2026-09-22). TWO REGISTRIES DISAGREED AND THE LEGACY ONE WAS
# WIRED. `ml_learning_surface_aliases` records `moment_suggestion` as
# ambiguous legacy vocabulary that may not receive canonical writes, while
# this map still offered it as something to export, fine-tune, promote and
# serve. One of the two has to be the authority, and it is the canonical one.
#
# Two moves, because either alone leaves a way back in: the surface is gone
# from SURFACES above, and `contract_for_surface` below re-checks the
# canonical registry on every lookup, so re-adding the entry would not
# resurrect the lane. Deliberately NOT an import-time assertion — this module
# is on the serving path for every LLM call, and a module that refuses to
# import is a broken live loop, which is a worse failure than the one being
# fixed.
#
# `services.moment_suggestions` still passes `surface="moment_suggestion"` to
# `chat_complete`. That is now an unknown surface, which `resolve_surface_model`
# already handles by returning the caller's own default — which is the point.

_FIELD_TO_SURFACE = {
    field: contract.id
    for contract in SURFACES.values()
    for field in contract.annotation_fields
}
_ALIAS_TO_SURFACE = {
    alias: contract.id
    for contract in SURFACES.values()
    for alias in contract.runtime_aliases
}
_ALIAS_TO_SURFACE.update({key: key for key in SURFACES})
_SAFE_ID = re.compile(r"^[a-z][a-z0-9_]{1,63}$")


def contract_for_surface(surface: str) -> SurfaceContract:
    raw = str(surface or "").strip().lower()
    canonical = _ALIAS_TO_SURFACE.get(raw)
    if not canonical or not _SAFE_ID.fullmatch(canonical):
        raise ValueError(
            f"Unknown trainable surface {surface!r}; choose one of "
            f"{sorted(SURFACES)}"
        )
    if raw in REJECTED_LEARNING_ALIASES or canonical in REJECTED_LEARNING_ALIASES:
        raise ValueError(
            f"{surface!r} is ambiguous legacy vocabulary the canonical "
            "registry rejects for learning writes; it cannot be exported, "
            "fine-tuned, promoted or served (audit E-6)"
        )
    return SURFACES[canonical]


def surface_for_annotation_field(field_name: str) -> Optional[str]:
    return _FIELD_TO_SURFACE.get(str(field_name or "").strip())


def fields_for_surface(surface: str) -> set[str]:
    return set(contract_for_surface(surface).annotation_fields)


def runtime_config_key(surface: str) -> str:
    return contract_for_surface(surface).runtime_config_key


# Golden evaluations need to run the real production adapter against a
# candidate model before that model is promoted.  A ContextVar scopes the
# override to that evaluation process/call chain; production requests cannot
# activate it through input, headers, or runtime configuration.
_EVAL_MODEL_OVERRIDES: contextvars.ContextVar[dict[str, str]] = \
    contextvars.ContextVar("willab_eval_model_overrides", default={})


@contextmanager
def evaluation_model_override(surface: str, model_id: str) -> Iterator[None]:
    contract = contract_for_surface(surface)
    model = str(model_id or "").strip()
    if not model:
        raise ValueError("model_id is required")
    current = dict(_EVAL_MODEL_OVERRIDES.get())
    current[contract.id] = model
    token = _EVAL_MODEL_OVERRIDES.set(current)
    try:
        yield
    finally:
        _EVAL_MODEL_OVERRIDES.reset(token)


def active_evaluation_override(surface: str) -> Optional[str]:
    """The ContextVar override for ``surface``, if one is active here.

    The promotion gate deliberately does NOT cover this: a golden evaluation
    runs the candidate through the real serving adapter while the gate is
    still shut, because passing that evaluation is what the founder opens the
    gate ON. The override is process-local and cannot be set by a request,
    a header or a database row — see `evaluation_model_override`.
    """
    try:
        contract = contract_for_surface(surface)
    except ValueError:
        return None
    return _EVAL_MODEL_OVERRIDES.get().get(contract.id) or None


_MODEL_CACHE: dict[str, tuple[float, Optional[str]]] = {}
_MODEL_CACHE_LOCK = threading.Lock()
_MODEL_CACHE_TTL_SECONDS = 60.0


def clear_runtime_model_cache() -> None:
    with _MODEL_CACHE_LOCK:
        _MODEL_CACHE.clear()


def resolve_surface_model(
    surface: str,
    default_model: str,
    *,
    config_getter: Callable[[str], object] | None = None,
) -> str:
    """Resolve a promoted model only for a registered trainable surface."""
    fallback = str(default_model or "").strip()
    try:
        contract = contract_for_surface(surface)
    except ValueError:
        return fallback

    override = _EVAL_MODEL_OVERRIDES.get().get(contract.id)
    if override:
        return override

    now = time.monotonic()
    with _MODEL_CACHE_LOCK:
        cached = _MODEL_CACHE.get(contract.id)
        if cached and now - cached[0] < _MODEL_CACHE_TTL_SECONDS:
            return cached[1] or fallback

    # LEGACY-1 / J1-2 (audit 2026-09-22). THE PROMOTION GATE, NOT THE ROW.
    # This read is what put a promoted fine-tune on the Take-1 Ideal Text
    # composition and every Say It Stronger card within sixty seconds of an
    # operator writing one row, while `MLC2_PROMOTION_ENABLED` stayed False
    # and the HTTP surface still answered "promotion is not active".
    #
    # The read is fenced, not removed: when the founder opens the gate the
    # stored model is served exactly as before, and until then the row is
    # inert. `resolve_gated_model` logs `promotion_disabled` so that "a model
    # is configured and withheld" is distinguishable from "none is
    # configured", which it was not.
    value: Optional[str] = None
    try:
        from services.runtime_model_gate import resolve_gated_model

        if config_getter is None:
            from services.db import db
            config_getter = db.get_runtime_config
        value = resolve_gated_model(
            contract.runtime_config_key, read=config_getter,
        )
    except Exception:
        value = None
    with _MODEL_CACHE_LOCK:
        _MODEL_CACHE[contract.id] = (now, value)
    return value or fallback


# ── H-1: a promoted model is bound to the prompt it was evaluated under ───
#
# The promotion gate already runs the candidate through the real serving
# adapter on golden cases, so a model that cannot answer in the serving shape
# is rejected before `runtime_config` is written. What it never recorded is
# WHICH PROMPT that evaluation used: the export JSONL carries no prompt
# version and `runtime_config` stored only a model id. A later prompt edit
# therefore re-points a promoted model at text it was never gated against,
# and nothing can notice.
#
# `locked_prompt_hash` is that missing binding — one digest over every
# `prompts.lock.json` entry belonging to the surface. `promote_openai_model`
# requires it on the command line and stores it beside the model id, so a
# prompt edit is visible as a mismatch rather than as silence.
#
# It is a record, not a re-evaluation. The export/serve prompt DIVERGENCE
# that H-1 also names belongs to Workstream 6 and is untouched here.
def _prompt_id_prefixes(contract: SurfaceContract) -> tuple[str, ...]:
    """Every lockfile id namespace this surface's prompts live under."""
    return tuple(sorted({
        contract.id, contract.golden_eval_surface, *contract.runtime_aliases,
    }))


def locked_prompt_hash(surface: str) -> str:
    """sha256 over the locked prompt digests of one trainable surface."""
    import hashlib

    from services.prompts.registry import read_lockfile

    contract = contract_for_surface(surface)
    prefixes = _prompt_id_prefixes(contract)
    locked = read_lockfile()
    entries = sorted(
        (pid, str(entry.get("sha256") or ""))
        for pid, entry in locked.items()
        if any(pid == p or pid.startswith(f"{p}.") for p in prefixes)
    )
    if not entries:
        raise ValueError(
            f"no locked prompts for surface {contract.id!r}; run "
            "`python -m services.prompts.registry update` first"
        )
    digest = hashlib.sha256()
    for pid, sha in entries:
        digest.update(f"{pid}:{sha}\n".encode("utf-8"))
    return digest.hexdigest()
