"""Canonical contracts for coach-correctable LLM surfaces.

One surface owns one annotation-field set, one golden evaluation adapter, and
one runtime model slot.  Keeping this mapping in one place prevents a model
trained on one kind of correction from leaking into an unrelated generator.
"""
from __future__ import annotations

import contextvars
import re
import threading
import time
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Callable, Iterator, Optional


@dataclass(frozen=True)
class SurfaceContract:
    id: str
    annotation_fields: tuple[str, ...]
    runtime_aliases: tuple[str, ...]
    golden_eval_surface: str

    @property
    def runtime_config_key(self) -> str:
        return f"openai_surface_model_{self.id}"


SURFACES: dict[str, SurfaceContract] = {
    "say_it_stronger": SurfaceContract(
        id="say_it_stronger",
        annotation_fields=("say_it_stronger",),
        runtime_aliases=("say_it_stronger",),
        golden_eval_surface="say_it_stronger",
    ),
    "moment_suggestion": SurfaceContract(
        id="moment_suggestion",
        annotation_fields=("moment_suggestion",),
        runtime_aliases=("moment_suggestion",),
        golden_eval_surface="moment_suggestion",
    ),
    # This is the contextual presentation-coach note, generated by
    # ``services.coach_comment_drafter`` and corrected in
    # ``coach_snippet_drafts.note``.  It is deliberately NOT the older
    # one-sentence ``admin_comment``/``snippet_drafts`` task: those prompts
    # and outputs have different semantics and must not share a corpus or a
    # promoted model merely because both happen to be called "comments".
    "coach_comment_draft": SurfaceContract(
        id="coach_comment_draft",
        annotation_fields=("coach_note",),
        runtime_aliases=("coach_comment_draft",),
        golden_eval_surface="coach_comment_draft",
    ),
    # ``best_presentation`` is the historical code/eval name.  The product
    # abstraction is Ideal Text, so both names resolve to one model slot.
    "ideal_text": SurfaceContract(
        id="ideal_text",
        annotation_fields=("ideal_text_sentence", "ideal_text_block"),
        runtime_aliases=("ideal_text", "best_presentation"),
        golden_eval_surface="best_presentation",
    ),
}

_FIELD_TO_SURFACE = {
    field: contract.id
    for contract in SURFACES.values()
    for field in contract.annotation_fields
}
_ALIAS_TO_SURFACE = {
    alias: contract.id
    for contract in SURFACES.values()
    for alias in contract.runtime_aliases
}
_ALIAS_TO_SURFACE.update({key: key for key in SURFACES})
_SAFE_ID = re.compile(r"^[a-z][a-z0-9_]{1,63}$")


def contract_for_surface(surface: str) -> SurfaceContract:
    raw = str(surface or "").strip().lower()
    canonical = _ALIAS_TO_SURFACE.get(raw)
    if not canonical or not _SAFE_ID.fullmatch(canonical):
        raise ValueError(
            f"Unknown trainable surface {surface!r}; choose one of "
            f"{sorted(SURFACES)}"
        )
    return SURFACES[canonical]


def surface_for_annotation_field(field_name: str) -> Optional[str]:
    return _FIELD_TO_SURFACE.get(str(field_name or "").strip())


def fields_for_surface(surface: str) -> set[str]:
    return set(contract_for_surface(surface).annotation_fields)


def runtime_config_key(surface: str) -> str:
    return contract_for_surface(surface).runtime_config_key


# Golden evaluations need to run the real production adapter against a
# candidate model before that model is promoted.  A ContextVar scopes the
# override to that evaluation process/call chain; production requests cannot
# activate it through input, headers, or runtime configuration.
_EVAL_MODEL_OVERRIDES: contextvars.ContextVar[dict[str, str]] = \
    contextvars.ContextVar("willab_eval_model_overrides", default={})


@contextmanager
def evaluation_model_override(surface: str, model_id: str) -> Iterator[None]:
    contract = contract_for_surface(surface)
    model = str(model_id or "").strip()
    if not model:
        raise ValueError("model_id is required")
    current = dict(_EVAL_MODEL_OVERRIDES.get())
    current[contract.id] = model
    token = _EVAL_MODEL_OVERRIDES.set(current)
    try:
        yield
    finally:
        _EVAL_MODEL_OVERRIDES.reset(token)


_MODEL_CACHE: dict[str, tuple[float, Optional[str]]] = {}
_MODEL_CACHE_LOCK = threading.Lock()
_MODEL_CACHE_TTL_SECONDS = 60.0


def clear_runtime_model_cache() -> None:
    with _MODEL_CACHE_LOCK:
        _MODEL_CACHE.clear()


def resolve_surface_model(
    surface: str,
    default_model: str,
    *,
    config_getter: Callable[[str], object] | None = None,
) -> str:
    """Resolve a promoted model only for a registered trainable surface."""
    fallback = str(default_model or "").strip()
    try:
        contract = contract_for_surface(surface)
    except ValueError:
        return fallback

    override = _EVAL_MODEL_OVERRIDES.get().get(contract.id)
    if override:
        return override

    now = time.monotonic()
    with _MODEL_CACHE_LOCK:
        cached = _MODEL_CACHE.get(contract.id)
        if cached and now - cached[0] < _MODEL_CACHE_TTL_SECONDS:
            return cached[1] or fallback

    value: Optional[str] = None
    try:
        if config_getter is None:
            from services.db import db
            config_getter = db.get_runtime_config
        raw_value = config_getter(contract.runtime_config_key)
        # Mock objects, JSON objects, and malformed DB values must never be
        # stringified into an OpenAI model identifier.
        value = raw_value.strip() if isinstance(raw_value, str) else None
        value = value or None
    except Exception:
        value = None
    with _MODEL_CACHE_LOCK:
        _MODEL_CACHE[contract.id] = (now, value)
    return value or fallback
