-- The founder's read-only count for retention schedule v1.5 (decisions log
-- N50 item 5; legal/phase1-2026.1/22-retention-schedule-v1.5-what-v1.4-left-open-DRAFT.md).
--
-- WHAT IT IS. One SELECT. It reads, counts and prints; it writes nothing,
-- holds no lock past its own read, and running it twice changes nothing.
-- Paste it into the Supabase SQL editor, run it, and paste the result back.
--
-- WHAT IT PRINTS. One row per table and question, in this order:
--   * v1.4 §3: the five pre-migrations product tables v1.4 decided but the
--     deletion reaches only after a read-only look at production;
--   * v1.4 §5.1-§5.7, the tables P1-P7 decided: for P2 and P4 the split
--     v1.5 makes by the row's own columns; for P5 the preview of the four
--     retired corpora the deletion now deletes (their rows and how many
--     people they belong to) and the six that still stop it;
--   * the rows the deletion KEEPS that point at a table v1.5 deletes: each
--     one stops a deletion for review before anything is deleted, until the
--     founder decides it (the speaker's rewrite answers, kept as an empty
--     receipt by N12; the coaching bundle's delivery jobs, kept 12 months as
--     job evidence; the learning lineage no subject graph reaches).
-- A table this database does not have prints a row that says so, with no
-- count, instead of stopping the query. Each count is exact (count(*)).

SELECT t.section,
       t.table_name,
       CASE WHEN to_regclass('public.' || t.table_name) IS NULL THEN NULL
            ELSE (xpath('/row/n/text()', query_to_xml(
                     format('SELECT %s AS n FROM public.%I%s', t.expression,
                            t.table_name,
                            COALESCE(' WHERE ' || t.condition, '')),
                     false, true, '')))[1]::text::bigint
       END AS count,
       CASE WHEN to_regclass('public.' || t.table_name) IS NULL
            THEN 'table not present in this database'
            ELSE t.question
       END AS what_is_counted
  FROM (VALUES
    (1, 'v1.4 §3 (waits for this check)', 'recording_sessions', 'count(*)', NULL, 'rows'),
    (2, 'v1.4 §3 (waits for this check)', 'pre_recording_answers', 'count(*)', NULL, 'rows'),
    (3, 'v1.4 §3 (waits for this check)', 'post_recording_answers', 'count(*)', NULL, 'rows'),
    (4, 'v1.4 §3 (waits for this check)', 'tasks', 'count(*)', NULL, 'rows'),
    (5, 'v1.4 §3 (waits for this check)', 'performance_scores', 'count(*)', NULL, 'rows'),
    (6, '§5.1 P1, the nine live records', 'learning_surface_presentations', 'count(*)', NULL, 'rows'),
    (7, '§5.1 P1, the nine live records', 'learning_surface_exposure_receipts', 'count(*)', NULL, 'rows'),
    (8, '§5.1 P1, the nine live records', 'ideal_text_user_edit_cas_operations', 'count(*)', NULL, 'rows'),
    (9, '§5.1 P1, the nine live records', 'confident_moment_text_update_capabilities', 'count(*)', NULL, 'rows'),
    (10, '§5.1 P1, the nine live records', 'feedback_v3_memberships', 'count(*)', NULL, 'rows'),
    (11, '§5.1 P1, the nine live records', 'feedback_v3_membership_items', 'count(*)', NULL, 'rows'),
    (12, '§5.1 P1, the nine live records', 'feedback_v3_owner_responses', 'count(*)', NULL, 'rows'),
    (13, '§5.1 P1, the nine live records', 'feedback_v3_service_render_receipts', 'count(*)', NULL, 'rows'),
    (14, '§5.1 P1, the nine live records', 'feedback_v3_service_response_bindings', 'count(*)', NULL, 'rows'),
    (15, '§5.2 P2', 'arc_purchases', 'count(*)', 'kind = ''founding_pass'' AND source = ''invite_code'' AND amount_minor IS NULL AND credits_charged IS NULL AND stripe_session_id IS NULL', 'free founding passes: deleted with the account'),
    (16, '§5.2 P2', 'arc_purchases', 'count(*)', 'source IN (''credits'', ''stripe'')', 'paid in credits or through Stripe: kept five years'),
    (17, '§5.2 P2', 'arc_purchases', 'count(*)', 'NOT ((kind = ''founding_pass'' AND source = ''invite_code'' AND amount_minor IS NULL AND credits_charged IS NULL AND stripe_session_id IS NULL) OR source IN (''credits'', ''stripe''))', 'neither: still stops a deletion for review'),
    (18, '§5.3 P3', 'ml_consent_snapshots', 'count(*)', NULL, 'kept six years as consent evidence'),
    (19, '§5.3 P3', 'ml_consent_events', 'count(*)', NULL, 'kept six years as consent evidence (already, v1.2)'),
    (20, '§5.4 P4', 'admin_uploaded_reference_videos', 'count(*)', 'is_universal', 'library content: the speaker''s link is cleared'),
    (21, '§5.4 P4', 'admin_uploaded_reference_videos', 'count(*)', 'NOT is_universal', 'made for a speaker: its file stops a deletion for review'),
    (22, '§5.5 P5', 'charisma_snippets', 'count(*)', NULL, 'rows: still stop a deletion for review'),
    (23, '§5.5 P5', 'stress_snippets', 'count(*)', NULL, 'rows: still stop a deletion for review'),
    (24, '§5.5 P5', 'acoustic_labels', 'count(*)', NULL, 'rows: still stop a deletion for review'),
    (25, '§5.5 P5', 'recording_review_annotations', 'count(*)', NULL, 'rows: deleted with their owner''s account (preview)'),
    (26, '§5.5 P5', 'recording_review_annotations', 'count(DISTINCT session_id)', NULL, 'owners those rows belong to (preview)'),
    (27, '§5.5 P5', 'recording_reviews', 'count(*)', NULL, 'rows: deleted with their owner''s account (preview)'),
    (28, '§5.5 P5', 'recording_reviews', 'count(DISTINCT session_id)', NULL, 'owners those rows belong to (preview)'),
    (29, '§5.5 P5', 'reflection_clips', 'count(*)', NULL, 'rows: deleted with their owner''s account (preview)'),
    (30, '§5.5 P5', 'reflection_clips', 'count(DISTINCT user_id)', NULL, 'owners those rows belong to (preview)'),
    (31, '§5.5 P5', 'shadow_predictions', 'count(*)', NULL, 'rows: still stop a deletion for review'),
    (32, '§5.5 P5', 'snippet_labels', 'count(*)', NULL, 'rows: still stop a deletion for review'),
    (33, '§5.5 P5', 'strong_sides_library', 'count(*)', NULL, 'rows: deleted with their owner''s account (preview)'),
    (34, '§5.5 P5', 'strong_sides_library', 'count(DISTINCT user_id)', NULL, 'owners those rows belong to (preview)'),
    (35, '§5.5 P5', 'training_labels', 'count(*)', NULL, 'rows: still stop a deletion for review'),
    (36, '§5.6 P6', 'ml_speaker_principals', 'count(*)', NULL, 'rows'),
    (37, '§5.6 P6', 'ml_purge_requests', 'count(*)', NULL, 'rows'),
    (38, '§5.6 P6', 'ml_canonical_events', 'count(*)', NULL, 'rows'),
    (39, '§5.6 P6', 'ml_object_artifacts', 'count(*)', NULL, 'rows'),
    (40, '§5.6 P6', 'ml_evidence_spans', 'count(*)', NULL, 'rows'),
    (41, '§5.6 P6', 'ml_product_actions', 'count(*)', NULL, 'rows'),
    (42, '§5.6 P6', 'ml_candidate_sets', 'count(*)', NULL, 'rows'),
    (43, '§5.6 P6', 'ml_confidence_producer_receipts', 'count(*)', NULL, 'rows'),
    (44, '§5.6 P6', 'dataset_split_assignments', 'count(*)', NULL, 'rows'),
    (45, '§5.6 P6', 'dataset_release_items', 'count(*)', NULL, 'rows'),
    (46, '§5.6 P6', 'dataset_exclusions', 'count(*)', NULL, 'rows'),
    (47, '§5.6 P6', 'take_feedback_policy_v3_shadow_frames', 'count(*)', NULL, 'rows'),
    (48, '§5.6 P6', 'take_feedback_detector_reconciliation', 'count(*)', NULL, 'rows'),
    (49, '§5.6 P6', 'exercise_authorization_checks', 'count(*)', NULL, 'rows'),
    (50, '§5.6 P6', 'learning_profiles', 'count(*)', NULL, 'rows'),
    (51, '§5.6 P6', 'exercise_audio_lineages', 'count(*)', NULL, 'rows'),
    (52, '§5.6 P6', 'exercise_blind_packets', 'count(*)', NULL, 'rows'),
    (53, '§5.6 P6', 'exercise_blind_packet_events', 'count(*)', NULL, 'rows'),
    (54, '§5.6 P6', 'learning_profile_observations', 'count(*)', NULL, 'rows'),
    (55, '§5.6 P6', 'exercise_selection_feature_snapshots', 'count(*)', NULL, 'rows'),
    (56, '§5.6 P6', 'exercise_candidate_sets', 'count(*)', NULL, 'rows'),
    (57, '§5.6 P6', 'exercise_candidates', 'count(*)', NULL, 'rows'),
    (58, '§5.6 P6', 'exercise_assignments', 'count(*)', NULL, 'rows'),
    (59, '§5.6 P6', 'exercise_randomization_assignments', 'count(*)', NULL, 'rows'),
    (60, '§5.6 P6', 'exercise_requests', 'count(*)', NULL, 'rows'),
    (61, '§5.6 P6', 'exercise_n1_source_pattern_results', 'count(*)', NULL, 'rows'),
    (62, '§5.6 P6', 'exercise_n1_pattern_snapshots', 'count(*)', NULL, 'rows'),
    (63, '§5.6 P6', 'exercise_n1_pattern_candidates', 'count(*)', NULL, 'rows'),
    (64, '§5.6 P6', 'exercise_practice_sessions', 'count(*)', NULL, 'rows'),
    (65, '§5.6 P6', 'exercise_practice_upload_recoveries', 'count(*)', NULL, 'rows'),
    (66, '§5.6 P6', 'exercise_practice_attempts', 'count(*)', NULL, 'rows'),
    (67, '§5.6 P6', 'exercise_practice_measurement_revisions', 'count(*)', NULL, 'rows'),
    (68, '§5.6 P6', 'exercise_practice_validity_assessments', 'count(*)', NULL, 'rows'),
    (69, '§5.6 P6', 'exercise_practice_selection_revisions', 'count(*)', NULL, 'rows'),
    (70, '§5.6 P6', 'exercise_practice_events', 'count(*)', NULL, 'rows'),
    (71, '§5.6 P6', 'exercise_service_offers', 'count(*)', NULL, 'rows'),
    (72, '§5.6 P6', 'exercise_service_offer_candidates', 'count(*)', NULL, 'rows'),
    (73, '§5.6 P6', 'exercise_service_offer_events', 'count(*)', NULL, 'rows'),
    (74, '§5.6 P6', 'exercise_pair_revisions', 'count(*)', NULL, 'rows'),
    (75, '§5.6 P6', 'exercise_pair_assignments', 'count(*)', NULL, 'rows'),
    (76, '§5.6 P6', 'exercise_pair_judgments', 'count(*)', NULL, 'rows'),
    (77, '§5.6 P6', 'exercise_reviewer_context_events', 'count(*)', NULL, 'rows'),
    (78, '§5.6 P6', 'exercise_service_requests', 'count(*)', NULL, 'rows'),
    (79, '§5.6 P6', 'exercise_authoring_drafts', 'count(*)', NULL, 'rows'),
    (80, '§5.6 P6', 'exercise_service_acquisition_receipts', 'count(*)', NULL, 'rows'),
    (81, '§5.6 P6', 'exercise_practice_transcription_runs', 'count(*)', NULL, 'rows'),
    (82, '§5.6 P6', 'exercise_service_confidence_assignments', 'count(*)', NULL, 'rows'),
    (83, '§5.6 P6', 'exercise_service_confidence_render_receipts', 'count(*)', NULL, 'rows'),
    (84, '§5.6 P6', 'exercise_service_confidence_judgments', 'count(*)', NULL, 'rows'),
    (85, '§5.6 P6', 'exercise_service_blind_review_sets', 'count(*)', NULL, 'rows'),
    (86, '§5.6 P6', 'exercise_service_blind_reveal_grants', 'count(*)', NULL, 'rows'),
    (87, '§5.6 P6', 'exercise_service_blind_reveal_accesses', 'count(*)', NULL, 'rows'),
    (88, '§5.6 P6', 'mlc3_service_principal_allowlist', 'count(*)', NULL, 'rows'),
    (89, '§5.6 P6', 'mlc3_service_cohort_members', 'count(*)', NULL, 'rows'),
    (90, '§5.6 P6', 'mlc3_service_enrollment_revisions', 'count(*)', NULL, 'rows'),
    (91, '§5.6 P6', 'mlc3_service_access_events', 'count(*)', NULL, 'rows'),
    (92, '§5.6 P6', 'mlc3_speaker_acquisition_revisions', 'count(*)', NULL, 'rows'),
    (93, '§5.6 P6', 'mlc3_self_speaker_assertions', 'count(*)', NULL, 'rows'),
    (94, '§5.6 P6', 'mlc3_target_speaker_bindings', 'count(*)', NULL, 'rows'),
    (95, '§5.6 P6', 'mlc3_comparison_speaker_eligibility_revisions', 'count(*)', NULL, 'rows'),
    (96, '§5.6 P6', 'confident_moment_bundle_attachments', 'count(*)', NULL, 'rows'),
    (97, '§5.6 P6', 'confident_moment_owner_decision_bindings', 'count(*)', NULL, 'rows'),
    (98, '§5.6 P6', 'root_phrase_coverage_frames', 'count(*)', NULL, 'rows'),
    (99, '§5.6 P6', 'root_phrase_coverage_items', 'count(*)', NULL, 'rows'),
    (100, '§5.6 P6', 'feedback_language_revision_deliveries', 'count(*)', NULL, 'rows'),
    (101, '§5.6 P6', 'feedback_revisions', 'count(*)', NULL, 'rows'),
    (102, '§5.6 P6', 'confident_moment_bundle_projections', 'count(*)', NULL, 'rows'),
    (103, '§5.6 P6', 'confident_moment_bundle_projection_items', 'count(*)', NULL, 'rows'),
    (104, '§5.6 P6', 'confident_moment_bundle_text_update_bindings', 'count(*)', NULL, 'rows'),
    (105, '§5.6 P6', 'confident_moment_coach_authorability_inventories', 'count(*)', NULL, 'rows'),
    (106, '§5.6 P6', 'confident_moment_coach_authorability_items', 'count(*)', NULL, 'rows'),
    (107, '§5.6 P6', 'confident_moment_blind_assignment_bindings', 'count(*)', NULL, 'rows'),
    (108, '§5.6 P6', 'confident_moment_coach_wording_authority_bindings', 'count(*)', NULL, 'rows'),
    (109, '§5.6 P6', 'root_phrase_content_versions', 'count(*)', NULL, 'rows'),
    (110, '§5.6 P6', 'root_phrase_semantic_input_snapshots', 'count(*)', NULL, 'rows'),
    (111, '§5.6 P6', 'root_phrase_semantic_results', 'count(*)', NULL, 'rows'),
    (112, '§5.6 P6', 'root_phrase_owner_alignment_actions', 'count(*)', NULL, 'rows'),
    (113, '§5.6 P6', 'root_phrase_qualification_revisions', 'count(*)', NULL, 'rows'),
    (114, '§5.6 P6', 'root_phrase_product_actions', 'count(*)', NULL, 'rows'),
    (115, '§5.6 P6', 'root_phrase_block_heads', 'count(*)', NULL, 'rows'),
    (116, '§5.6 P6', 'coach_guidance_review_frames', 'count(*)', NULL, 'rows'),
    (117, '§5.6 P6', 'coach_guidance_review_frame_items', 'count(*)', NULL, 'rows'),
    (118, '§5.6 P6', 'coach_guidance_review_batches', 'count(*)', NULL, 'rows'),
    (119, '§5.6 P6', 'coach_guidance_reveal_grants', 'count(*)', NULL, 'rows'),
    (120, '§5.6 P6', 'coach_guidance_reveal_grant_judgments', 'count(*)', NULL, 'rows'),
    (121, '§5.6 P6', 'coach_guidance_reveal_accesses', 'count(*)', NULL, 'rows'),
    (122, '§5.6 P6', 'coach_guidance_media_bindings', 'count(*)', NULL, 'rows'),
    (123, '§5.6 P6', 'coach_guidance_upload_permits', 'count(*)', NULL, 'rows'),
    (124, '§5.6 P6', 'coach_guidance_upload_recoveries', 'count(*)', NULL, 'rows'),
    (125, '§5.6 P6', 'coach_guidance_upload_events', 'count(*)', NULL, 'rows'),
    (126, '§5.6 P6', 'coach_guidance_media_validity_events', 'count(*)', NULL, 'rows'),
    (127, '§5.6 P6', 'coach_guidance_independent_media_reviews', 'count(*)', NULL, 'rows'),
    (128, '§5.6 P6', 'coach_guidance_attachments', 'count(*)', NULL, 'rows'),
    (129, '§5.6 P6', 'coach_guidance_attachment_versions', 'count(*)', NULL, 'rows'),
    (130, '§5.6 P6', 'coach_guidance_lifecycle_events', 'count(*)', NULL, 'rows'),
    (131, '§5.6 P6', 'coach_guidance_publications', 'count(*)', NULL, 'rows'),
    (132, '§5.6 P6', 'coach_guidance_publication_invalidations', 'count(*)', NULL, 'rows'),
    (133, '§5.6 P6', 'coach_inline_source_roles', 'count(*)', NULL, 'rows'),
    (134, '§5.6 P6', 'coach_inline_exercise_drafts', 'count(*)', NULL, 'rows'),
    (135, '§5.6 P6', 'coach_inline_context_assessments', 'count(*)', NULL, 'rows'),
    (136, '§5.6 P6', 'coach_inline_exercise_eligibility_reviews', 'count(*)', NULL, 'rows'),
    (137, '§5.7 P7 (the clean-up''s)', 'token_ledger', 'count(*)', NULL, 'rows'),
    (138, '§5.7 P7 (the clean-up''s)', 'llm_usage', 'count(*)', NULL, 'rows'),
    (139, 'kept rows that point at v1.5''s', 'correction_decisions', 'count(*)', 'feedback_membership_id IS NOT NULL', 'the speaker''s rewrite answers, kept (N12), pointing at a V3 item'),
    (140, 'kept rows that point at v1.5''s', 'feedback_language_delivery_materialization_jobs', 'count(*)', NULL, 'delivery jobs, kept as job evidence, pointing at a bundle row'),
    (141, 'kept rows that point at v1.5''s', 'ml_candidates', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (142, 'kept rows that point at v1.5''s', 'ml_classification_runs', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (143, 'kept rows that point at v1.5''s', 'ml_confidence_blind_packets', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (144, 'kept rows that point at v1.5''s', 'ml_judgments', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (145, 'kept rows that point at v1.5''s', 'ml_machine_predictions', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (146, 'kept rows that point at v1.5''s', 'ml_model_runs', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (147, 'kept rows that point at v1.5''s', 'ml_object_verifications', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (148, 'kept rows that point at v1.5''s', 'ml_presentations', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (149, 'kept rows that point at v1.5''s', 'ml_purge_events', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (150, 'kept rows that point at v1.5''s', 'ml_rendered_exposures', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (151, 'kept rows that point at v1.5''s', 'ml_review_assignment_events', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (152, 'kept rows that point at v1.5''s', 'ml_review_assignments', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (153, 'kept rows that point at v1.5''s', 'ml_selection_runs', 'count(*)', NULL, 'learning lineage no graph reaches'),
    (154, 'kept rows that point at v1.5''s', 'ml_semantic_artifacts', 'count(*)', NULL, 'learning lineage no graph reaches')
  ) AS t(position, section, table_name, expression, condition, question)
 ORDER BY t.position;
