-- Retention report: what the cleaner WOULD delete. Read-only; changes nothing.
-- Founder 2026-10-05 (decisions log N45): "Q3b 30 days", "Q4 yes as
-- recommended" — the cleaner shows the list before its first real run, and
-- the real run waits for the founder's word.
--
-- RUN IN THE SUPABASE SQL EDITOR. One SELECT. One row per rule and line;
-- nothing is listed by person.
--
-- ONE DEFINITION (migrations 0423, old_data_goes_on_a_schedule.sql, and
-- 0426, financial_records_go_after_five_years.sql). This file reads
-- public.retention_report_v1, and so does every run of the cleaner
-- (services/retention_cleaner.py): a dry run records exactly these lines,
-- and a live run deletes exactly what they count. The functions it reads
-- are declared STABLE or IMMUTABLE, so the database itself refuses any
-- change made through them.
--
-- THE FOUR RULES
--   1. An unclaimed guest's recordings go 30 days after the guest was created
--      (a guest who signed up is claimed and is never counted; a guest whose
--      erasure has finished is not counted again).
--   2. Audio goes 12 months after last use, with its voice measurements.
--      NOTHING RECORDS "LAST USE": no column says when a recording was last
--      opened or played. The founder defined it (2026-10-05,
--      decisions log N46: "12 months without the activity is the last used")
--      as the later of
--        (a) when the recording was made, and
--        (b) the last change to any project of its owner
--      (a claimed guest's recordings count under the account that claimed
--      them). Only recordings in processing_audio_objects are counted, and
--      only while no deletion is recorded for them: the older tables that
--      hold audio without its fingerprint (recordings, snippets, practice
--      attempts, uploads) are not covered yet. A recording whose person or
--      project is being erased is left to that erasure.
--      The "voice measurements" lines count what goes with that audio, by
--      store: the Take's measurement columns are emptied, its measurement
--      rows removed, and an account's aggregates go with its last recording.
--   3. Technical logs go 90 days after creation. Only these tables, named
--      one by one: processing_jobs, life_reminder_log,
--      admin_annotations_log, mlc3_service_backpressure_events. A
--      processing_jobs row that deletion evidence points at is kept, and
--      counted on its own line. dev_bugs is the founder's own bug list, not
--      a log, and is never counted (decisions log N50, C4 B). Evidence
--      tables (authorization, deletion, provider operations, claims) are
--      never on this list.
--   4. Financial records (token_ledger, llm_usage) go when their five years
--      end: five years from the end of the financial year in which each was
--      made (retention schedule v1.3; decisions log N50, P7), the calendar
--      year in Polish time. A row made in 2026 is due from 1 January 2032.
--      Every account's, open or deleted; a row whose account is being
--      erased waits for that erasure, which keeps it.
--
-- What a run did: scripts/retention_cleaner_runs.sql.

SELECT rule, would_delete, how_many
  FROM public.retention_report_v1(now())
 ORDER BY 1, 2;
